name: python

on: [push, pull_request]

jobs:
  python:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        LCG: ["LCG_96b/x86_64-centos7-gcc9-opt"]
    steps:
    - uses: actions/checkout@v2
    - name: Install CVMFS
      run: |
        wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
        sudo dpkg -i cvmfs-release-latest_all.deb
        sudo apt-get update
        sudo apt-get install cvmfs cvmfs-config-default
        wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
        sudo mkdir -p /etc/cvmfs
        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config setup
        ls /cvmfs/sft.cern.ch
        ls /cvmfs/geant4.cern.ch
    - name: Start container
      run: |
        docker run -it --name CI_container -v /home/runner/work/podio/podio:/Package -e VIEW=${{ matrix.LCG }} -v /cvmfs:/cvmfs -d clicdp/cc7-lcg96b /bin/bash
    - name: Run Python Checks
      continue-on-error: ${{matrix.LCG == 'LCG_96b/x86_64-centos7-gcc9-opt' }}
      run: |
        docker exec CI_container /bin/bash -c "./Package/.github/scripts/runPythonChecks.sh"
